/* empty css                      */(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const f="https://your-energy.b.goit.study/api";window.addEventListener("DOMContentLoaded",()=>{console.log("JS WORKING"),h(),E()});function h(){const r=document.getElementById("quote"),t=document.getElementById("author");!r||!t||fetch(`${f}/quote`).then(n=>n.json()).then(n=>{r.textContent=n.quote,t.textContent=n.author}).catch(()=>{r.textContent="Error loading quote"})}let a="Muscles",u="",d=1,p="";function E(){console.log("=== ИНИЦИАЛИЗАЦИЯ ===");const r=document.getElementById("exercises");r&&(r.innerHTML="",console.log("Контейнер упражнений очищен"));const t=document.querySelectorAll("#filters button[data-filter]");console.log("Найдено кнопок фильтров:",t.length),t.forEach((l,e)=>{console.log(`Фильтр кнопка ${e}: ${l.getAttribute("data-filter")}`),l.addEventListener("click",function(o){o.preventDefault(),o.stopPropagation();const c=this.getAttribute("data-filter");console.log(`
>>> НАЖАТА КНОПКА ФИЛЬТРА:`,c),a=c,u="",d=1,m()})});const n=document.getElementById("search");n&&n.addEventListener("keydown",l=>{l.key==="Enter"&&(p=l.target.value,console.log("Поиск:",p),y())}),console.log("Загрузка начальных категорий..."),m(),console.log(`=== ИНИЦИАЛИЗАЦИЯ ЗАВЕРШЕНА ===
`)}function m(){console.log(`
=== loadCategories ===`),console.log("Фильтр:",a);const r=`${f}/filters?filter=${a}`;console.log("URL:",r),fetch(r).then(t=>t.json()).then(t=>{console.log("Ответ API категории:",t.results?t.results.length+" категорий":"ошибка");const n=document.getElementById("categories");if(!n){console.error("ОШИБКА: #categories не найден!");return}if(n.innerHTML="",!t.results||t.results.length===0){console.log("Категории не найдены"),n.innerHTML="<p>Нет категорий</p>";return}console.log("Создание "+t.results.length+" кнопок категорий..."),t.results.forEach((l,e)=>{const o=document.createElement("button");o.textContent=l.name,o.type="button",o.style.border="1px solid #ccc",o.style.margin="5px",o.style.padding="10px 15px",o.style.borderRadius="10px",o.style.cursor="pointer",o.style.background="#fff",o.style.fontSize="14px",o.onclick=function(c){return function(s){s&&(s.preventDefault(),s.stopPropagation()),console.log(`
>>> НАЖАТА КНОПКА КАТЕГОРИИ: `+c),console.log("Текущий фильтр: "+a);const i=document.getElementById("exercises");i&&(i.innerHTML=""),u=c,d=1,console.log("category установлена: "+u),console.log("filter: "+a),console.log("Вызов loadExercises()..."),y()}}(l.name),console.log(`  Кнопка ${e+1}: ${l.name}`),n.appendChild(o)}),console.log("Все "+t.results.length+" кнопок добавлены")}).catch(t=>{console.error("ОШИБКА loadCategories:",t)})}function y(r=1){console.log(`
=== loadExercises ВЫЗВАНА ===`),console.log("Параметры: p="+r+", category="+u+", filter="+a),d=r;const t=document.getElementById("exercises");if(!t){console.error("NO #exercises IN HTML");return}if(!u){console.warn("NO CATEGORY SELECTED - category пуста"),t.innerHTML="<p>Выберите категорию</p>";return}let n="";if(a==="Muscles"?n="muscle":a==="Body parts"?n="bodyPart":a==="Equipment"&&(n="equipment"),!n){console.error("Неизвестный фильтр:",a);return}console.log("Определен param:",n);let l=`${f}/exercises?${n}=${encodeURIComponent(u)}&page=${d}&limit=10`;p&&(l+=`&keyword=${encodeURIComponent(p)}`),console.log("=== ПОЛНЫЙ URL ==="),console.log(l),console.log("==="),t.innerHTML="<p>Загрузка упражнений для: "+u+"...</p>",fetch(l).then(e=>{if(console.log("Статус ответа:",e.status,e.statusText),!e.ok)throw new Error("HTTP Error: "+e.status);return e.json()}).then(e=>{if(console.log("=== ОТВЕТ API ==="),console.log("Всего результатов:",e.results?e.results.length:0),console.log("Всего страниц:",e.totalPages),console.log("Данные:",e),console.log("==="),t.innerHTML="",!e.results||e.results.length===0){t.innerHTML=`<p>Нет упражнений для вида "<b>${u}</b>" 😢</p>`,console.warn("Упражнения не найдены для категории:",u);return}console.log("Рендер "+e.results.length+" упражнений..."),e.results.forEach((o,c)=>{console.log(`  Упражнение ${c+1}: ${o.name} (Target: ${o.target}, Equipment: ${o.equipment})`);const s=document.createElement("div");s.style.border="1px solid #ddd",s.style.margin="10px 0",s.style.borderRadius="8px",s.style.background="#fff",s.style.overflow="hidden";const i=document.createElement("div");i.style.padding="15px",i.style.cursor="pointer",i.style.backgroundColor="#f5f5f5",i.style.fontWeight="bold",i.style.userSelect="none",i.innerHTML=o.name;const g=document.createElement("div");g.style.padding="15px",g.style.display="block",g.style.borderTop="1px solid #eee",g.innerHTML=`
          <p><strong>Target:</strong> ${o.target||"N/A"}</p>
          <p><strong>Equipment:</strong> ${o.equipment||"N/A"}</p>
          <p><strong>Body part:</strong> ${o.bodyPart||"N/A"}</p>
          <button data-id="${o._id}" style="padding: 8px 16px; cursor: pointer; background: #007bff; color: white; border: none; border-radius: 4px;">Details</button>
        `,i.addEventListener("click",()=>{g.style.display=g.style.display==="none"?"block":"none"}),s.appendChild(i),s.appendChild(g),t.appendChild(s)}),console.log("Рендер завершен, всего упражнений отрисовано:",e.results.length),b(),x(e.totalPages)}).catch(e=>{console.error("=== ОШИБКА FETCH ==="),console.error("Ошибка:",e),console.error("Message:",e.message),t.innerHTML="<p>Ошибка загрузки упражнений: "+e.message+"</p>"})}function b(){document.querySelectorAll("[data-id]").forEach(r=>{r.onclick=()=>{fetch(`${f}/exercises/${r.dataset.id}`).then(t=>t.json()).then(t=>{alert(`${t.name}

${t.description}`)})}})}function x(r){const t=document.getElementById("pagination");if(t){console.log(`
=== ПАГИНАЦИЯ ===`),console.log("Всего страниц:",r),t.innerHTML="";for(let n=1;n<=r;n++){const l=document.createElement("button");l.textContent=n,l.style.margin="5px",l.style.padding="5px 10px",l.style.cursor="pointer",l.style.border="1px solid #ccc",l.style.borderRadius="4px",l.style.backgroundColor=d===n?"#007bff":"#fff",l.style.color=d===n?"#fff":"#000",l.onclick=function(e){return function(o){o&&(o.preventDefault(),o.stopPropagation()),console.log(`
>>> НАЖАТА СТРАНИЦА:`,e),console.log("Текущая категория:",u),console.log("Текущий фильтр:",a),d=e,console.log("page установлена:",d),console.log("Вызов loadExercises("+e+")..."),y(e)}}(n),t.appendChild(l)}console.log("Создано "+r+" кнопок пагинации")}}
//# sourceMappingURL=index.js.map
